# Generated by Django 3.1.3 on 2021-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('password', models.TextField(max_length=1000)),
                ('objective', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to=None, verbose_name='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
