# Generated by Django 3.1.3 on 2021-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipes_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_type', models.TextField(max_length=1000)),
                ('name', models.TextField(max_length=1000)),
                ('ingredients', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to=None, verbose_name='')),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
