# Generated by Django 3.1.3 on 2021-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.TextField(max_length=1000)),
                ('name', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to=None, verbose_name='')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='')),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='')),
            ],
            options={
                'db_table': 'dietary',
            },
        ),
    ]
